<div class="row">
  @include('admin.partials._select', ['name'=>'branch_id','label'=>"Branch",'value'=>$model->branch_id ?? '','options'=>$branches,'labelKey'=>'name_en','col'=>4,'required'=>true])
  @include('admin.partials._select', ['name'=>'current_class_id','label'=>"Class",'value'=>$model->current_class_id ?? '','options'=>$classes,'col'=>4,'required'=>false])
  @include('admin.partials._select', ['name'=>'academic_year_id','label'=>"Academic Year",'value'=>$model->academic_year_id ?? '','options'=>$academicYears,'col'=>4,'required'=>false])
  @include('admin.partials._select', ['name'=>'shift_id','label'=>"Shift",'value'=>$model->shift_id ?? '','options'=>$shifts,'col'=>4,'required'=>false])
  @include('admin.partials._input', ['name'=>'student_code','label'=>"Student Code",'value'=>$model->student_code ?? '','col'=>4,'required'=>true,'type'=>'text'])
  @include('admin.partials._input', ['name'=>'student_no','label'=>"Student #",'value'=>$model->student_no ?? '','col'=>4,'required'=>false,'type'=>'text'])
  @include('admin.partials._input', ['name'=>'name_en','label'=>"Name (EN)",'value'=>$model->name_en ?? '','col'=>4,'required'=>true,'type'=>'text'])
  @include('admin.partials._input', ['name'=>'name_kh','label'=>"Name (KH)",'value'=>$model->name_kh ?? '','col'=>4,'required'=>false,'type'=>'text'])
  @include('admin.partials._select', ['name'=>'gender','label'=>"Gender",'value'=>$model->gender ?? '','options'=>[['id'=>'male','display'=>'Male'], ['id'=>'female','display'=>'Female'], ['id'=>'other','display'=>'Other']],'col'=>4,'required'=>false])
  @include('admin.partials._input', ['name'=>'date_of_birth','label'=>"Date of Birth",'value'=>$model->date_of_birth ?? '','col'=>4,'required'=>false,'type'=>'date'])
  @include('admin.partials._input', ['name'=>'phone','label'=>"Phone",'value'=>$model->phone ?? '','col'=>4,'required'=>false,'type'=>'tel'])
  @include('admin.partials._textarea', ['name'=>'address','label'=>"Address",'value'=>$model->address ?? '','rows'=>3,'required'=>false])
  @include('admin.partials._input', ['name'=>'qr_code_value','label'=>"QR Code Value",'value'=>$model->qr_code_value ?? '','col'=>4,'required'=>false,'type'=>'text'])
  @include('admin.partials._input', ['name'=>'barcode_value','label'=>"Barcode",'value'=>$model->barcode_value ?? '','col'=>4,'required'=>false,'type'=>'text'])
  @include('admin.partials._input', ['name'=>'rfid_uid','label'=>"RFID UID",'value'=>$model->rfid_uid ?? '','col'=>4,'required'=>false,'type'=>'text'])
  @include('admin.partials._select', ['name'=>'status','label'=>"Status",'value'=>$model->status ?? '','options'=>[['id'=>'active','display'=>'Active'], ['id'=>'studying','display'=>'Studying'], ['id'=>'suspended','display'=>'Suspended'], ['id'=>'dropout','display'=>'Dropout'], ['id'=>'graduated','display'=>'Graduated'], ['id'=>'transferred','display'=>'Transferred']],'col'=>4,'required'=>true])
  @include('admin.partials._input', ['name'=>'admission_date','label'=>"Admission Date",'value'=>$model->admission_date ?? '','col'=>4,'required'=>false,'type'=>'date'])
  @include('admin.partials._input', ['name'=>'exit_date','label'=>"Exit Date",'value'=>$model->exit_date ?? '','col'=>4,'required'=>false,'type'=>'date'])
</div>
